-- =============================================================================
-- 02_ddl_silver.sql
-- CMS Open Payments — General Payments PY2025 — silver typed table
-- -----------------------------------------------------------------------------
-- Matches silver.general_payments in the modeling.db catalog.
-- Typed and cleaned, one row per Record_ID (dedupe happens in the load, not
-- via a constraint). Loaded from bronze by section 2 of 03_load.sql, which
-- also needs the silver.clean_str / to_date / to_bool macros.
-- Idempotent (IF NOT EXISTS).
-- Usage   : duckdb -bail modeling.db < 02_ddl_silver.sql
-- =============================================================================

CREATE SCHEMA IF NOT EXISTS silver;

CREATE TABLE IF NOT EXISTS silver.general_payments (
    Change_Type                                                           VARCHAR,
    Covered_Recipient_Type                                                VARCHAR,
    Teaching_Hospital_CCN                                                 VARCHAR,
    Teaching_Hospital_ID                                                  BIGINT,
    Teaching_Hospital_Name                                                VARCHAR,
    Covered_Recipient_Profile_ID                                          BIGINT,
    Covered_Recipient_NPI                                                 BIGINT,
    Covered_Recipient_First_Name                                          VARCHAR,
    Covered_Recipient_Middle_Name                                         VARCHAR,
    Covered_Recipient_Last_Name                                           VARCHAR,
    Covered_Recipient_Name_Suffix                                         VARCHAR,
    Recipient_Primary_Business_Street_Address_Line1                       VARCHAR,
    Recipient_Primary_Business_Street_Address_Line2                       VARCHAR,
    Recipient_City                                                        VARCHAR,
    Recipient_State                                                       VARCHAR,
    Recipient_Zip_Code                                                    VARCHAR,
    Recipient_Country                                                     VARCHAR,
    Recipient_Province                                                    VARCHAR,
    Recipient_Postal_Code                                                 VARCHAR,
    Covered_Recipient_Primary_Type_1                                      VARCHAR,
    Covered_Recipient_Primary_Type_2                                      VARCHAR,
    Covered_Recipient_Primary_Type_3                                      VARCHAR,
    Covered_Recipient_Primary_Type_4                                      VARCHAR,
    Covered_Recipient_Primary_Type_5                                      VARCHAR,
    Covered_Recipient_Primary_Type_6                                      VARCHAR,
    Covered_Recipient_Specialty_1                                         VARCHAR,
    Covered_Recipient_Specialty_2                                         VARCHAR,
    Covered_Recipient_Specialty_3                                         VARCHAR,
    Covered_Recipient_Specialty_4                                         VARCHAR,
    Covered_Recipient_Specialty_5                                         VARCHAR,
    Covered_Recipient_Specialty_6                                         VARCHAR,
    Covered_Recipient_License_State_code1                                 VARCHAR,
    Covered_Recipient_License_State_code2                                 VARCHAR,
    Covered_Recipient_License_State_code3                                 VARCHAR,
    Covered_Recipient_License_State_code4                                 VARCHAR,
    Covered_Recipient_License_State_code5                                 VARCHAR,
    Submitting_Applicable_Manufacturer_or_Applicable_GPO_Name             VARCHAR,
    Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_ID           BIGINT,
    Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Name         VARCHAR,
    Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_State        VARCHAR,
    Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Country      VARCHAR,
    Total_Amount_of_Payment_USDollars                                     DECIMAL(18,2),
    Date_of_Payment                                                       DATE,
    Number_of_Payments_Included_in_Total_Amount                           BIGINT,
    Form_of_Payment_or_Transfer_of_Value                                  VARCHAR,
    Nature_of_Payment_or_Transfer_of_Value                                VARCHAR,
    City_of_Travel                                                        VARCHAR,
    State_of_Travel                                                       VARCHAR,
    Country_of_Travel                                                     VARCHAR,
    Physician_Ownership_Indicator                                         BOOLEAN,
    Third_Party_Payment_Recipient_Indicator                               VARCHAR,
    Name_of_Third_Party_Entity_Receiving_Payment_or_Transfer_of_Value     VARCHAR,
    Charity_Indicator                                                     BOOLEAN,
    Third_Party_Equals_Covered_Recipient_Indicator                        BOOLEAN,
    Contextual_Information                                                VARCHAR,
    Delay_in_Publication_Indicator                                        BOOLEAN,
    Record_ID                                                             BIGINT,
    Dispute_Status_for_Publication                                        BOOLEAN,
    Related_Product_Indicator                                             BOOLEAN,
    Covered_or_Noncovered_Indicator_1                                     VARCHAR,
    Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_1             VARCHAR,
    Product_Category_or_Therapeutic_Area_1                                VARCHAR,
    Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_1              VARCHAR,
    Associated_Drug_or_Biological_NDC_1                                   VARCHAR,
    Associated_Device_or_Medical_Supply_PDI_1                             VARCHAR,
    Covered_or_Noncovered_Indicator_2                                     VARCHAR,
    Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_2             VARCHAR,
    Product_Category_or_Therapeutic_Area_2                                VARCHAR,
    Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_2              VARCHAR,
    Associated_Drug_or_Biological_NDC_2                                   VARCHAR,
    Associated_Device_or_Medical_Supply_PDI_2                             VARCHAR,
    Covered_or_Noncovered_Indicator_3                                     VARCHAR,
    Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_3             VARCHAR,
    Product_Category_or_Therapeutic_Area_3                                VARCHAR,
    Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_3              VARCHAR,
    Associated_Drug_or_Biological_NDC_3                                   VARCHAR,
    Associated_Device_or_Medical_Supply_PDI_3                             VARCHAR,
    Covered_or_Noncovered_Indicator_4                                     VARCHAR,
    Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_4             VARCHAR,
    Product_Category_or_Therapeutic_Area_4                                VARCHAR,
    Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_4              VARCHAR,
    Associated_Drug_or_Biological_NDC_4                                   VARCHAR,
    Associated_Device_or_Medical_Supply_PDI_4                             VARCHAR,
    Covered_or_Noncovered_Indicator_5                                     VARCHAR,
    Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_5             VARCHAR,
    Product_Category_or_Therapeutic_Area_5                                VARCHAR,
    Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_5              VARCHAR,
    Associated_Drug_or_Biological_NDC_5                                   VARCHAR,
    Associated_Device_or_Medical_Supply_PDI_5                             VARCHAR,
    Program_Year                                                          BIGINT,
    Payment_Publication_Date                                              DATE,
    _source_file                                                          VARCHAR,
    _loaded_at                                                            TIMESTAMP
);
